import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    config_container: {
      flex: 1,
      backgroundColor: '#EDF1D6',
      alignItems: 'center',
      justifyContent: 'flex-start',
      height: '100vh',
    },
    config_title_container:{
      width: '100%',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: '20%',
      // borderColor: 'red',
      // borderWidth: 1,
    },
    config_title: {
      fontSize: 24,
      fontWeight: 'bold',
      color: '#40513B',
    },
    config_default_container:{
      width: '100%',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 47,
      // borderColor: 'red',
      // borderWidth: 1,
    },
    config_default:{
      width: '77%',
      height: 57,
      display: 'flex',
      alignItems: 'flex-start',
      justifyContent: 'center',
      borderRadius: 8,
      backgroundColor: '#D26E28',
      paddingLeft: 11,
    },
    config_name:{
      color: "#FFFFFF",
      fontWeight: "bold",
      fontSize: 17,
    },
    config_stats_container:{
      display: 'flex',
      flexDirection: 'row',
    },
    config_stats:{
      color: "#FFFFFF",
      fontSize: 14,
    },
    config_number:{
      color: "#FFFFFF",
      fontWeight: "bold",
      fontSize: 14,
    },
    config_create_conteiner:{
      width: '100%',
      marginTop: 50,
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 30,
      // borderColor: 'red',
      // borderWidth: 1,
    },
    config_create:{
      width: '88%',
      display: 'flex',
      flexDirection: 'row',
      justifyContent:  'space-between',
      alignItems: 'flex-start',
      borderBottomWidth: 2, 
      borderBottomColor: '#40513B',
      paddingHorizontal: 16,
    },
    config_create_title:{
      fontSize: 20,
      fontWeight: 'bold',
      color: '#40513B',
    },
    config_all_container:{
      display: 'flex',
      justifyContent:  'center',
      alignItems: 'center',
      width: '100%',
    },
    configuracao:{
      display: 'flex',
      justifyContent: 'center',
      width: '77%',
      height: 60,
      backgroundColor: '#40513B',
      borderRadius: 8,
      marginBottom: 24,
      paddingLeft: 9,
      gap: 3,
    },
    iconConfig:{
      position: 'absolute',
      right: '5%',
      bottom: '20%',
    },
    updateConfig:{
      position: 'absolute',
      right: '15%',
      bottom: '20%',
    },
    container_text:{
        width: '100%',
        height:'3%',
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: '5%',
        marginBottom: '3%',
        marginLeft: '10%',
        marginRight:'10%',
        borderBottomColor: 'black',
        borderBottomWidth: 1,
        borderColor: 'red',
        borderWidth: 1,
    },
    contentContainer:{
        flexGrow: 1, // isso que faz o scrollview funcionar 
    },
    bottomBar_container:{
        backgroundColor: '#EDF1D6',
        position: 'absolute',
        width: '100%',
        height: 95,
        bottom: 0,
    },
});
